# .github/docker/Dockerfile.tomcat-it
ARG TOMCAT_TAG=9.0.117-jre21-temurin
FROM tomcat:${TOMCAT_TAG}

RUN rm -rf /usr/local/tomcat/webapps/*
COPY it-webapp/target/it-webapp.war /usr/local/tomcat/webapps/ROOT.war
