language: java

dist: trusty

jobs:
  include:
    - name: OpenJDK 8
      jdk: openjdk8
    - name: OracleJDK 8
      jdk: oraclejdk8
    - name: OpenJDK 11
      jdk: openjdk11
    - name: OracleJDK 11
      jdk: oraclejdk11

cache:
  directories:
    - "$HOME/.m2"


script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Password4j_password4j

addons:
  sonarcloud:
    organization: "password4j"
    token:
      secure: "fOMRFobabbo2jRdm9BH8Z0VVgwKvQO1Y/6V5jTgiNGrhQn7G0CSFkIQZ7H0rYUPP6SVu/gvVssOU6qf/yGTLjMmcOVsjxbmGxcrf2UQ2MAUkHHIicuMDrHKsu68rsSySlqKUzQ3PxXr6Uh5UdsxUsc12WvuYbMdkiyvypSlq+xKD0trslOMSsA2ALwIyDx7O2b3lHMLD5Jd+bi+WswSGtltpAIv6rG1HyDWfwCpiuRLf9cIPvcQRZmtBnPd+aOGuzYfhep9jA2Y95nWrYC21aoW29LWFMik1lXzgd+yZfJ/86ebskVpB/FaVH6D8sJA9FNDBWaGFwFUMKZp4VF8Bjw6wNJLDpMO9v1QHS6S3RcVSHr8nBNtay4m015Mfa8OATuRDZ3+gBrLns/kPnVATq/pUiE6u7NUZYn7z7PrfyS5fT3R7R671RGB2pvGC6CBzjF9+NGaveMNKjcVqzPBV/oSA1Q+D30ah28XOvu0Kk63jBiLiBoLRz2rJpQncNlK+lt0ELMER4IF0LThReWp3/bQwwVP6qFWCG+oc0HfIZnS12gu0iKDWqZmqzJwPFJvE61Hj8lSYa2vCcDglz4w4WKSTiIExOpWZu7Gjmp+eZVhKvRKq2Ovek21ZI4UN7Bo20tF9cXscHsyAx8HTV0F0UsIvaroUS06xB1spIo3nTV4="
